### ISSUE TITLE
openssh pubkey ECDSA vs RSA mismatch

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#10]
Fabric (paramiko?) uses RSA to verify the identity of the remote ssh-host.

If an ECDSA public key for the same remote host is included in the local known_hosts file, this will cause openssh to prompt for confirmation, which will break fabric scripts which have set:

 `api.env.abort_on_prompts = True`

**Comment by Liz315** [comment]
We don't have any Fabric code anymore.
