### ISSUE TITLE
out of fds

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#161]
As reported in email, our web site failed when we got popular last night, due to running out of fds. A possible solution which would raise the number of simultaneous visitors that it can handle, from 256 to maybe 1024, would be to use this code at the beginning of launching our web server:

https://tahoe-lafs.org/trac/tahoe-lafs/browser/trunk/src/allmydata/util/iputil.py?annotate=blame&rev=b0883807361830c609dff1677c3cb34fd64d3ebb#L12

**Comment by Liz315** [comment]
After the new website is deployed, this will be mostly resolved. For the signups server, we'll need to do this before we get super popular.
