### ISSUE TITLE
broken link to National Cyber-Security Initiative Report

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#169]
The rotating list of glow-quotes on our home page has a link to a "National Cybersecurity Initiative report" that is now a broken link. Fix this by just making it into a non-link description, or by finding or hosting a copy of the PDF report and linking to that.

See also https://zooko.com/uri/URI:DIR2-MDMF-RO:dwvqalbdt4ax4vgupcewxljg3u:bej7hhojmpuugy77oyydmazf6uu7huiipkctih7adky7e6txavnq/klog.html#%5B%5Bnational%20cyber%20defense%20report%20recommends%20Tahoe-LAFS%5D%5D for a description of that National Cybersecurity Initiative and a link (probably also broken!) to the PDF report document.

**Comment by daira** [comment]
Fixed in [72b9c4e5fae58a9180dcce6ac3ad86be87d60c9a] but not yet deployed.

**Comment by daira** [comment]
Deployed.
