### ISSUE TITLE
why did it take a few seconds to load the form?

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#171]
I clicked on "Sign me up!" and a few seconds later the Stripe form loaded. Why did it take so long? It took so long that I had time to read the message "Loading... If the form doesn't load please contact LeastAuthority.com...".

To fix this ticket, make it load so fast that I can't even blink before it is loaded.

Note: I am _not_ marking this ticket as a stripe-deployment-blocker.

**Comment by Liz315** [comment]
Closing due to time since this bug was reported and a low likeliness that we'll be able to recreate it.
