### ISSUE TITLE
Failures during provisioning _MUST_ reliably send email to support@leastauthority.com

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#187]
During signup earthrise and zooko were told (in a freshly rendered webpage) that their payment credentials had been processed and that they should be receiving a confirmation email with a furl shortly.

The above was all correct, but the subsequent provisioning process on which their service depends, then broke.

And _THEN_ support@leastauthority.com was _not_ sent an email informing them of this _DIRE_ failure.

**Comment by Liz315** [comment]
A monitoring system should get a blip, not an email.
