### ISSUE TITLE
Deployments Cause production outage

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#192]
Currently runs of 'deploy_infrastructure_server.py --existing_host' reboot the target server.   This is not sustainable if the production server starts to experience high traffic.

**Comment by exarkun** [comment]
The website is now deployed independently of the infrastructure servers.  Combined with the infrastructure servers running as containers managed by Kubernetes, this is more or less resolved - or at least, resolveable.  Using Kubernetes rolling updates should avoid downtime while the new deployment is set up and the old is taken down.
