### ISSUE TITLE
deploy infrastrucure server bugs

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#203]
(0) too many parameters

consider defaults values

(1) poorly named secrets
(2) incoherent separation of key IDs into and out of files
(3) too much is done for simple repo updates

functionalize procedures, also helps with testing, bug isolation etc.

(4) unix file system permissions prevent ssh
(5) server privkey fingerprint must be loaded into .ssh/known_hosts
(6) it extremely easy to publish production secrets too the testingacctataws
(7) there are obsolete values in the secret_config repo and lae_automation_config.json

**Comment by exarkun** [comment]
Deploy infrastructure replaced by Kubernetes.
