### ISSUE TITLE
Slight instruction flaw for GPG use.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#218]
The signup page https://leastauthority.com/s4-subscription-form says:

```
Tell us your public key — please paste the ASCII-armored public key block here. 
You can get it using gpg --export -a YOUR_EMAIL_ADDRESS.
```

For me, this gpg command will export the wrong key because I have multiple keys associated with my email address, and this command either selects a single key arbitrarily or exports all keys (I forget which).

**Comment by daira** [comment]
We no longer support gpg.
