### ISSUE TITLE
What is the user policy for ec2 access?

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#240]
Without knowing about the deployment complexity, I advocate this policy for all of our ec2s:
1. Each person who needs access to a host must have a dedicated user account.
2. If we also have per `(user, host)` ssh key policy as in #2, then this hosts user account should only have ssh pubkeys which belong to one or more `(user, host)` pairs controlled by a single human.  (Note, one human should not have ssh access to more than one account, and one account should only have ssh access based on keys controlled by one human.)
3. For commands which require "system" accounts which control machine-wide resources, such as `website`, each such commands should always be executed as a "human user account" with `sudo -u $SYSTEM_ACCOUNT_NAME $COMMAND $ARGS`.
4. Restrict all system accounts so that it is impossible to ssh into them, and it is impossible to su to them.  The goal is that the _only_ way to execute commands as such a system user is with `sudo -u`.

**Why?**

By default, on debian-like systems, every `sudo` invocation is logged into `/var/log/auth.log`.  If every system operation must be initiated by `sudo`, then this log will provide a log of system operations.  By having separate user accounts, we have some indication which human (or compromised account) initiated each operation.

Additionally, the same log file shows all ssh accesses, so if we have the separate-keys policy in #2, we will have a single log file that shows all ssh accesses and all sudo command.

**Example:**

``` bash
$ ssh [HOST REDACTED]
Linux [HOST REDACTED] 2.6.39.1-linode34 #1 SMP Tue Jun 21 10:29:24 EDT 2011 i686 GNU/Linux
Ubuntu 10.04.1 LTS

Welcome to Ubuntu!
 * Documentation:  https://help.ubuntu.com/
Last login: Fri Jun 13 21:55:50 2014 from 70-36-196-174.dsl.static.sonic.net

  -{ 2014-06-18 16:29:56 | $?=0 | 0 jobs | n@[HOST REDACTED]:~ }-


$ sudo -u sshd whoami
[sudo] password for n:
sshd

  -{ 2014-06-18 16:30:14 | $?=0 | 0 jobs | n@[HOST REDACTED]:~ }-


$ tail /var/log/auth.log
Jun 18 16:22:27 de sshd[4450]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=117.21.226.164  user=root
Jun 18 16:22:28 de sshd[4450]: Failed password for root from 117.21.226.164 port 1045 ssh2
Jun 18 16:22:39 de sshd[4450]: last message repeated 5 times
Jun 18 16:22:39 de sshd[4450]: PAM 5 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=117.21.226.164  user=root
Jun 18 16:22:39 de sshd[4450]: PAM service(sshd) ignoring max retries; 6 > 3
Jun 18 16:29:55 de sshd[4452]: Accepted publickey for n from 99.127.229.99 port 51055 ssh2
Jun 18 16:29:55 de sshd[4452]: pam_env(sshd:setcred): Unable to open env file: /etc/default/locale: No such file or directory
Jun 18 16:29:55 de sshd[4452]: pam_unix(sshd:session): session opened for user n by (uid=0)
Jun 18 16:29:55 de sshd[4464]: pam_env(sshd:setcred): Unable to open env file: /etc/default/locale: No such file or directory
Jun 18 16:30:14 de sudo:        n : TTY=pts/0 ; PWD=/home/n ; USER=sshd ; COMMAND=/usr/bin/whoami
```

**Side Note:** Notice the break-in attempts against sshd in the example.  Time to disable password-based logins and rhost everything there!  Anecdotally, I've seen those kinds of attempts on multiple hosts for many months and I assume they are standard botnet scans.  If anyone else could verify they see similar scans on arbitrary hosts, that would be good!

**Comment by Liz315** [comment]
This is a valid question, but we'll evaluate it in the future and create new issues.
