### ISSUE TITLE
Execute an Amazon export of all customer S3 data to a physical location we control.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#242]
This is not a devops development task.  This is a "click the buttons and pay with your credit card to ship hard drives to our LLC address in as little time as possible" task.

Start here: https://aws.amazon.com/importexport/

**Comment by exarkun** [comment]
Not sure _why_ we would want to do this.  If someone can figure that out maybe we can work out a plan that makes sense.  Also, TLoS3 is pretty much done at this point.
