### ISSUE TITLE
I noticed that new SSEC2s have not successfully been update/upgraded

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#251]
I expected to find 0 unapplied security updates on new SSEC2s instead I noticed 26 on an SSEC2 I ssh'd into, and a 'restart required' warning.

**Comment by exarkun** [comment]
There won't be EC2 instances after we finish the Kubernetes switch.  Containers will need security updates, I'll file an issue for that.

**Comment by exarkun** [comment]
#466
