### ISSUE TITLE
Pull dependencies out into declarative lists.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#254]
**Summary:**

Specify all dependencies consistently as declarative lists like [TAHOE_LAFS_PACKAGE_DEPENDENCIES](https://github.com/LeastAuthority/leastauthority.com/blob/7b405e85aed90784cf3d56f14a42ec187c96ca1e/lae_automation/server.py#L142-L158).

**Rationale:**
Currently there is a mix of declarative lists as well as ad-hoc imperative installs in other areas.  A declarative list approach has several useful advantages:
- We can see the list of dependencies in one location (single source of truth).
- The code is more likely to install all dependencies in one phase, which is preferable for reasoning about the stages of deployment.

**Approach:**

There are several different package types: apt packages, wget-tarball-then-setup-install,  pip, and potentially others.  The goal for this ticket is to have declarative lists for each type.

Moving these lists into a singe python module could also be nice when reviewing diffs to quickly identify when dependencies change.

**Details:**

While reviewing recent changes to the deployment scripts I noticed several imperative lines for installing dependencies, such as [./lae_automation/server.py L351](https://github.com/LeastAuthority/leastauthority.com/blob/master/lae_automation/server.py#L351):

``` python
    sudo('pip install --index-url https://code.stripe.com --upgrade stripe')
    write(postfixdebconfstring, '/home/ubuntu/postfixdebconfs.txt')
    sudo('debconf-set-selections /home/ubuntu/postfixdebconfs.txt')
    sudo_apt_get('install -y postfix')
    sudo_apt_get('install -y darcs')

#    sudo_apt_get('install -y nginx')
#    write(NGINX_CONFIG, '/etc/nginx/sites-enabled/mailman', True)
#    sudo('rm /etc/nginx/sites-enabled/default')
#    sudo('service nginx restart')

    run('wget https://pypi.python.org/packages/source/p/pelican/pelican-3.2.2.tar.gz')
    run('tar zxf pelican-3.2.2.tar.gz')
    with cd('pelican-3.2.2'):
        sudo('python setup.py install')
```

Meanwhile there already _are_ some declarative lists, such as used in [Line 348](https://github.com/LeastAuthority/leastauthority.com/blob/master/lae_automation/server.py#L348):

``` python
    package_list = TAHOE_LAFS_PACKAGE_DEPENDENCIES + EXTRA_INFRASTRUCTURE_PACKAGE_DEPENDENCIES
    apt_install_dependencies(stdout, package_list)
```

**Comment by exarkun** [comment]
Obsoleted by some other work, mostly the switch to containers.
