### ISSUE TITLE
Trigger leastbot announcements on customer signups.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#256]
It would be nice to trigger leastbot announcements on customer signups.

A potentially dangerous way to do this is to add an http POST request to the signup automation.  This is dangerous because of potential failure cases, and we don't want new monitoring to introduce brittleness.

A "safer" way would be to have leastbot somehow triggered upon receiving signup email notifications from #255.  That ticket seems less brittle, since we are already depending on email sends.

OTOH, maybe making HTTP requests and recovering from any failure in the HTTP request is safe enough.  It's certainly easier to implement on the leastbot side, since leastbot already has an HTTP interface to receive github webhook event notifications.

**Comment by exarkun** [comment]
leastbot fell over, I guess, and we'll get reports from liz about signups.
