### ISSUE TITLE
Consider moving to debian-packages-only deployment process.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#257]
What if deployment to a host always looked like this:

``` bash
$ ssh $HOST
$ sudo apt-get update
$ sudo apt-get install leastauthority-website
```

This implies we have separate _deployment_ and _release_ processes, where the latter process starts from a set of git repositories and ends with placing newly built `.deb` files onto a debian packaging repository which we control.

This also implies that we solve all of the state modification issues that exist in deployment designs the debian way.  We can rely on debian conventions and standards and folk lore to solve new problems we encounter.

This ticket is pretty wide open, so maybe we could close it in one of two ways:
- closing it as "wontfix" because we decide not to do this because of a better alternative, or
- closing it after we've added many more specific tickets for making this transition.

We should solicit advice from devops people we know as to whether or not this is a good strategy and what the biggest pitfalls are.

**Comment by exarkun** [comment]
From the perspective of 2016, it seems like Docker containers make more sense than OS packages (sad to say).  Work on that front is progressing now (currently active ticket - #415).  I expect that work will obsolete this idea.

**Comment by exarkun** [comment]
With a bit more experience with the things, I still think containers are the right approach.  So no need to mess with Debian packages.
