### ISSUE TITLE
Make blog deployments "as transactional as possible".

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#259]
nathan-at-least commented 5 days ago

**Edit by @nathan-at-least on 2014-07-11**: I went to the old ticket, clicked the edit button on the description, then copied the _origin markup_ then pasted it here.  The old paste lost all markup.

**Requirements**

It would be nice if the automated process for deploying a new blog has (as much as possible) **properties** of a transaction from the perspective of website visitors:
1. HTTP requests prior to the successful completion of the post always return the previous released blog revision files.
2. HTTP requests subsequent to the successful completion of the post always return the newly released blog revision files.
3. There is no period of time, no matter how slow the webserver operates and how quickly HTTP clients make requests such that:
   1. an earlier request (to any path) returns a newer revision than:
   2. a subsequent request (to any other path), which returns an older revision
4. There is (ideally) no time during which any HTTP request fails to return a blog post (a temporary outage such as HTTP 404s).

**Related Tickest**
Meeting these properties _implies_ tickets #2 and #3 are also complete.

**Implementation**

I suggest this approach, which assumes these path definitions (all refer to paths which at some point contain directories):
- `$BLOG_SOURCE` - a copy of the correct revision of this `blog_source` repo on the target deployment host.  Note, this could be a git repo with `HEAD` at the correct revision and ideally no changed or unknown files, or it could be the result of scp'ing and untaring said revision, etc...
- `$RENDER_DEST` - a directory created as a temporary directory which will contain the render output and will be moved to the `$LIVE_DIR`.
- `$LIVE_DIR` - the path which the webserver reads from to serve HTTP requests to `/blog.*` paths.
- `$DEAD_DIR` - a temporary path which `$LIVE_DIR` is mv'd to prior to deletion.

Process:
1. On target server (testing/staging or production): retrieve and prepare the to-be-released revision of the blog source in `$BLOG_SOURCE`.  If this fails, abort, and notice that the blog source here may be borked.
2. Create `$RENDER_DEST`.  Importantly:
   1. This should be outside of the webserver root so that HTTP clients cannot access it.
   2. Ensure `$RENDER_DEST` ownership and permissions match `$LIVE_DIR`.
   3. Ensure `$RENDER_DEST` and `$LIVE_DIR` live on the same _filesystem device_.  (This ensures an `mv` is a simple modification of a directory inode, rather than a recursive copy of contents across devices.)
3. If rendering fails, abort.  This means `$RENDER_DEST` will be left in an incoherent state, and if these are not cleaned up the disk will fill up, but the properties 1-4 above will still be met.
4. `mv $LIVE_DIR $DEAD_DIR && mv $RENDER_DEST $LIVE_DIR`.  Note that between the two move operations, property 4 is not met, but placing these on the same shell command makes this time window as small as possible AFAIK.
5. If either mv operation failed, we've failed to meet the 1-4 properties.  Panic.  Sound the klaxxons.  Change the status indicators to red.  Send the on-call devops team alert SMSs.  ;-)
6. At this point is should be safe to `rm -r $DEAD_DIR`.  (Note: I recommend the `mv` then the `rm` because I assume the former is much faster, but I may be wrong.)

**Comment by Liz315** [comment]
Overcome by new site.
