### ISSUE TITLE
handle failure of rendering tool on production, correctly

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#260]
nathan-at-least commented 5 days ago

Another thought is that we don't need to do rendering on the webserver. We could have a deployment command that one runs from a local machine which does:

```
render to a fresh new directory,
tar the result up,
scp it to the webserver,
run the "deploy render tarball" script on the webserver.
```

This way, any errors in 1-3 won't affect the webserver at all, and the webserver will no longer run a rendering process (which could potentially bork the host) nor have that software installed (less code on the webserver is better). All of those justifications are "nice" but not necessary in the short term, so I say only do this scp approach if it's not much more work or other complexity.
zancas
zancas commented 2 days ago

+1 I like this approach.

**Comment by exarkun** [comment]
Switching to lektor.
