### ISSUE TITLE
ensure that old versions of rendered files are removed

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#261]
zancas commented 6 days ago

man pelican

shows:

-d, --delete-output-directory

I'm going to experiment with this flag in our blog rendering command:

8a1d7fd#diff-80d1211390dcefe3b3904114f787e067
nathan-at-least nathan-at-least referenced this issue 5 days ago
Closed
Make blog deployments "as transactional as possible". #6
nathan-at-least
nathan-at-least commented 5 days ago

This is ok, and acceptable (to me) in the short term. However, while it's deleting files or generating new files, requests to our blog will return 404 codes for some paths.

I wrote a slightly more involved, but "transactional" approach suggestion in #6. If that's not much more work, I'd recommend going with the #6 design.
zancas
zancas commented 2 days ago

Well, I'm not sure when pelican deletes the old posts, so it may already do the right thing. I'll investigate.
nathan-at-least
nathan-at-least commented 2 days ago

After today's standup, I believe rm -rf $RENDERED_DIR followed by rendering a newly created output into $RENDERED_DIR is preferable because: a. we all know what that does, b. it takes less time to research, c. is good enough for now.
zancas
zancas commented 2 days ago

I propose

mv $RENDERED_DIR $OLD_RENDERED_DIR_$(TIMESTAMP)

Instead of rm -rf.

**Comment by exarkun** [comment]
Switching to lektor.
