### ISSUE TITLE
Unwarranted guarantee in signup text.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#269]
I just applied for a new personal account and the result page from submitting my payment information says:

```
We are deploying the infrastructure necessary to support your Cloud service! We'll send you an email with your unique introducer furl within the next hour. 
```

I don't believe the promise of a 1 hour response time is true.  If not, we should not tell customers we will send them a furl within the hour.  I suspect that only PGP signups are non-automated, in which case only PGP signups take longer than an hour.

Maybe for _both_ cases it would be better to simply say:

```
We are deploying the infrastructure necessary to support your Cloud service!  We'll send you an email with your unique introducer furl soon. 
```

**Comment by Liz315** [comment]
Overcome by recent improvements.
