### ISSUE TITLE
Make Support/Zendesk stylistically consistent with https://leastauthority.com

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#27]
I noticed the following information about customizing our "support" page.

https://support.zendesk.com/entries/20269321-how-to-customize-the-help-desk-using-css

I don't think this is a high priority, but I think there would be a slight reduction in friction in the User experience if we were to homogenize style across our zendesk page(s).

**Comment by Liz315** [comment]
I've updated the support page to look like the rest of the site. We may want to have this professionally updated in the future. But for now, it is ok.
