### ISSUE TITLE
Usable-and-secure communication with customers

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#275]
I've been thinking about how to solve the "usable-and-secure communication with customers" problem.

PGP isn't usable. (Any dissent? :-) It might be an option that some users want because it
provides end-to-end security, but it's a pain to use and to automate, and it is very
security-error-prone.

Other secure communication protocols like OTR-over-XMPP are even less usable, and even more security-error-prone.

While there are several new projects attempting to address usably-secure communication, none of them is ready yet, and all of them require the user to install new software.

TLS mostly works and is usable, and doesn't require any software other than a web browser. It doesn't really provide end-to-end security because of the huge bag of dubious and untrustworthy CAs, but that's a separate previously unsolved problem.

Besides, we need TLS to work anyway in order for signup to be secure. So we aren't really losing much by depending on it after signup as well, other than giving attackers a
longer time window.

I therefore suggest that each customer has a capability URL of the form

`https://leastauthority.com/contact?key=<base32_sparse_capability>`

This "contact page" is also the page they land on immediately after a signup. They are
encouraged to bookmark it _and_ write the URL down on paper.

The contact page contains:
- their introducer furl;
- brief setup instructions, and a link to more detailed instructions;
- a simple chat webapp that allows anyone with the contact URL to add messages (maybe it also allows deleting messages given some extra capability, and maybe it    distinguishes messages written by LA employees given some other capability, but    those are not strictly necessary). Messages are date-stamped and displayed    most-recent-first.

That's it.

(For extra credit, put the sparse capability in a fragment rather than a queryarg.)

**Comment by Liz315** [comment]
Replaced by #465
