### ISSUE TITLE
Separate "runtime site code" from "deployment automation".

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#282]
I think we can and should separate the site's "runtime site code" from "deployment automation".

Note, the latter is specifically automation executed by ops engineers to upgrade/reconfigure/deploy to our infrastructure, _in contrast to_ `./lae_automation` which is runtime site code which automates our infrastructure to fulfill user signups.

Having this separation should make it easier to achieve the "local dev deployment" layer of #281.

I personally would propose we make the runtime site code a proper python package, so it will have a version which increments with our releases and our deployment process will install or upgrade it (with pip or setuptools or apt-get or whatever is best).  _Even if_ we don't use such a packaging system in our deployment for some reason, this allows local dev installations to rely on that packaging specification, which improves the chances that it is up to date and accurate (for local dev environments, at least).

If it were a package, then dependency management can rely on whichever packaging system we rely on, so that we could have a single source of truth for specifying dependencies.

The remaining deployment automation would fill in whatever gaps such as stateful changes which the runtime site code packaging doesn't capture.  For example, suppose we need to migrate customers in some set by altering only their state in some way in some process that takes a long time (and may not even interact with the production website host at all!) then that kind of process would live in the deployment automation codebase.

**Comment by Liz315** [comment]
After the new site is live we can finish by deleting the website code from the old repo.
