### ISSUE TITLE
S3 error "A conflicting conditional operation is currently in progress against this resource." during signup

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#3]
Originally reported by Zancas at [[https://tahoe-lafs.org/trac/tahoe-lafs/ticket/1994]].

I attempted to create an S3 bucket to use with the S3 backend (by signing up for the LeastAuthority cyphertext storage service). Here's a normal message printed during such a signup:

Creating S3 bucket in 'US East' region...

it was immediately followed by this error:

Failure notification sent for the following error: S3Error: Error Message: A conflicting conditional operation is currently in progress against this resource. Please try again. Command failed with exit code 1.

**Comment by Coupdag** [comment]
I had the same problem but got around it by using IAM credentials. The problem for me was, that I was trying to create bucket via cmd with master key credentials. Create user from IAM and add aws key id + secret key id and let's hope it works!

**Comment by Liz315** [comment]
Closing because we don't have enough information to resolve, now.

**Comment by nsisodiya** [comment]
I got this problem when I deleted my bucket from one account and trying to create on another account. (Same name)

**Comment by tommedema** [comment]
@daira did you ever resolve this?

**Comment by IMfenil** [comment]
If you are creating a new bucket after deleting old one with the same name , it will take around an hour for the reflection.

You can also refer [link](https://serverfault.com/questions/554374/how-long-before-an-s3-bucket-can-be-created-with-same-name-after-deletion)

**Comment by kartheekdabbiru97** [comment]
@nsisodiya I've encountered the same issue. Were you able to interpret why it's happening? If so what is the solution to resolve this error?

**Comment by Christopher-Hayes** [comment]
> @nsisodiya I've encountered the same issue. Were you able to interpret why it's happening? If so what is the solution to resolve this error?

What @IMfenil said. AWS puts the bucket in a queue to be deleted, which takes about an hour. So it's technically not deleted until AWS's backend has gotten around to deleting it. An hour or so later, creating a new bucket with the same name should work. Bucket names are **globally** unique, so this would happen across different accounts as well.
