### ISSUE TITLE
Transient S3 DNS failures generate multiservercheck.sh emails

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#30]
The report (email bodies + timestamps).  The times are the email header times reported by the sending agent.  They are ~10 minutes apart as expected

Time One:
'''
User-Agent: Least Authority Enterprises e-mail sender
From: Monitoring monitoring-bounces@leastauthority.com
Message-ID:20130721014101.13224.1468971777.1@ip->10-244-251-66.ec2.internal>
Date: Sun, 21 Jul 2013 01:41:01 +0000
To: monitoring@leastauthority.com
'''

Email One:
"""
Monitoring monitoring-bounces@leastauthority.com via gmail.com 

Jul 20 (4 days ago)

to monitoring
Hello, monitoring script here.

The following problem(s) may need investigation:

Error: Host 54.243.27.42 was not able to resolve 'lae-e11bac1d-b4vrhkerr75wthgbzkjr7uvj5jkwjqkm.s3.amazonaws.com':
';; connection timed out; no servers could be reached'
## 

multiservercheck.py

---

Monitoring mailing list
Monitoring@leastauthority.com
https://leastauthority.com:8443/cgi-bin/mailman/listinfo/monitoring
Monitoring monitoring-bounces@leastauthority.com via gmail.com 
"""

Time Two:
'''
User-Agent: Least Authority Enterprises e-mail sender
From: Monitoring monitoring-bounces@leastauthority.com
Message-ID:20130721015036.13804.1277515660.1@ip->10-244-251-66.ec2.internal>
Date: Sun, 21 Jul 2013 01:50:36 +0000
To: monitoring@leastauthority.com
'''

Body Two:
"""
Jul 20 (4 days ago)

to monitoring
Hello, monitoring script here.

Everything appears to be working again, as far as I can tell.
"""

**Comment by daira** [comment]
I made the nslookup done by the monitoring script retry once. If that eliminates the DNS failures from monitoring, we can consider them false alarms and close this ticket.

**Comment by Liz315** [comment]
multiservercheck.sh no longer exists.
