### ISSUE TITLE
Create an `analytics@` google/email account to allow processes on analytics to send email with host-scoped privileges / secrets.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#300]
@daira and I are working on monitoring deployment, and we realized we want separate google/email accounts for the monitoring processes on analytics versus rho so that each instance can have separate email/google credentials for better privilege separation.

Therefore we want a new `analytics@` account so that the analytics host can have only those credentials and not more general credentials (such as `info@`).

Note, for this separation to be effective we must also rotate the `info@` password.  See #299.

This is a (semi-) prerequisite for #270.

**Comment by exarkun** [comment]
The analytics host is gone.  We'll probably do reporting some other way, when we get to that point again.
