### ISSUE TITLE
create, or assign keyword to, tickets on Tahoe-LAFS trac for OpenITP Packaging Project

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#318]
Review the OpenITP Packaging Contract and make sure it is all done.

For each task that we said we would do in https://github.com/LeastAuthority/LeastAuthoritarians/blob/master/proposals/openitp-proposal_good-packaging-for-LAFS.rst, put that task into one of three categories:

1. It is done, and here's a link to a closed ticket or a deliverable that accomplished that task, on Tahoe-LAFS trac (https://tahoe-lafs.org/trac/tahoe-lafs/query?status=assigned&status=new&status=reopened&keywords=~openitp-packaging&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=milestone&col=component&order=priority), on github.com/LeastAuthority/LeastAuthoritarians (https://github.com/LeastAuthority/LeastAuthoritarians/labels/OpenITP%20Packaging%20Grant).
2. It is not done, and here's a link to an open ticket.
3. It isn't going to be done, because it has been superceded by other work that we did instead, and here is a link to a ticket, or description of the other work that supercedes it.

**Comment by zookoatleastauthoritycom** [comment]
I'd like to send OpenITP a set of hyperlinks to the appropriate tickets when I send them the invoice for the remainder of the money.

**Comment by daira** [comment]
The report Ramki and I are writing will contain these links.

**Comment by daira** [comment]
Fixed.
