### ISSUE TITLE
remove Reset The Net from our website

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#327]
We're done with Reset The Net. Strip the banners etc. (not the historical blog post) off our web site.

**Comment by david415** [comment]
i submitted two pull requests... one for the leastauthority.com repo and the other for the blog_source repo. Might there be other repositories with reset-the-net banners?

**Comment by daira** [comment]
Deployed.

**Comment by daira** [comment]
(No, there are no other relevant repos.)
