### ISSUE TITLE
documented automated setup of web server

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#342]
To close this ticket:
1. There is a script you can run that sets up an instance of the https://LeastAuthority.com web site and server.
2. There is a document that says how to run that script.
3. That document is discoverable to someone (e.g. a new employee) who looks for it on the wiki (https://github.com/LeastAuthority/leastauthority.com/wiki).
4. There are not "decoy documents" -- things that tell you incorrect or out-dated information about how to do this, or things that look like they are going to tell you how to do this, but it turns out they don't contain the necessary information.

Daira: will you please do the work to make the four things above true and then David, will you please act as the sample new employee, by going to the wiki and discovering correct and up-to-date information about how to do this?

**Comment by exarkun** [comment]
Deployment is now based on k8s and is documented in docs/operations.rst.
