### ISSUE TITLE
figure out if we can generate invoices/receipts

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#356]
A (potential) customer asked for this: https://leastauthority.zendesk.com/tickets/323?col=24856816&page=1

Could @daira and/or @david415 figure out if there is an easy way to get Stripe to generate these? If not, no problem, we just need to write back ASAP to the customer saying sorry we currently can't.

**Comment by daira** [comment]
Assigning to @david415 . If you need Stripe credentials to find this out, please ask.

**Comment by david415** [comment]
it doesn't seem to generate this on a per customer basis but it can e-mail when payment successful, export to quickbooks and csv; i looked at the csv file and it seems to be an aggregate of all customer payment info; can we close this ticket with a will not fix?

**Comment by daira** [comment]
I set it to generate receipts for each payment (for all customers) a while ago.
