### ISSUE TITLE
customer is waiting for cancellation!

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#357]
This customer asked to cancel back in January! That means he's been charged several times bogusly, or else that he had to cancel his credit card (which is a huge hassle and a black mark on our reputation):

https://leastauthority.zendesk.com/tickets/347?col=24856816&page=1

**Comment by daira** [comment]
I've processed this now. There were failed charges so he must have blocked his credit card.

**Comment by zookoatleastauthoritycom** [comment]
Could you write back to him and apologize again? Thanks!

**Comment by daira** [comment]
Already done.
