### ISSUE TITLE
add David to About Us!

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#358]
https://leastauthority.com/about_us

**Comment by zookoatleastauthoritycom** [comment]
Dear David: we're going to post a blog post about a bug that was reported in libsnark, and when we do some people are going to follow the link from that blog post to https://leastauthority.com/about_us . So would you please add yourself to https://leastauthority.com/about_us ASAP!?

**Comment by david415** [comment]
please review and advise how to improve this:
https://github.com/LeastAuthority/leastauthority.com/tree/358-add-david-to-aboutus

**Comment by david415** [comment]
https://github.com/LeastAuthority/leastauthority.com/pull/365

**Comment by david415** [comment]
done
