### ISSUE TITLE
remove the Bureaumancer job from the Careers page

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#360]
https://leastauthority.com/careers

After closing this ticket, the careers page should be empty, or perhaps should say "Check back soon for our next job openings…"

@david415: could you make this update to the site? It goes well with https://github.com/LeastAuthority/leastauthority.com/issues/358, which I want you to do soon.

**Comment by david415** [comment]
i think we can close this ticket since there isn't any careers page or link to a careers page.
