### ISSUE TITLE
"Stripe Invalid Request error" are noise that impedes processing of customer support requests

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [LeastAuthority/leastauthority.com#362]
There are a lot of these:

https://leastauthority.zendesk.com/tickets/358?col=24856811&page=1

They make it harder for me to respond to customer support requests.

Are they false alarms or true alarms? Is there anything I should do about them? If there is nothing that I can do about them could we make them stop going to zendesk at all?

**Comment by daira** [comment]
On 26/03/15 16:47, zookoatleastauthoritycom wrote:
> There are a lot of these:
> 
> https://leastauthority.zendesk.com/tickets/358?col=24856811&page=1
> 
> They make it harder for me to respond to customer support requests.
> 
> Are they false alarms or true alarms? Is there anything I should do about them? If there
> is nothing that I can do about them could we make them stop going to zendesk at all?

I believe these are all false alarms. I'll have a closer look and try to suppress them
if they are.

-- 
Daira Hopwood ⚥

**Comment by daira** [comment]
Might this be related to #215 ?

**Comment by daira** [comment]
We worked out that this is caused by a GET request to ``https://leastauthority.com/submit-subscription``.

**Comment by meejah** [comment]
See https://github.com/LeastAuthority/leastauthority.com/pull/399
