### ISSUE TITLE
Fix CSS style for blog footnotes.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#372]
Currently, footnote definitions appear as red text on a grey background.  This is difficult to read.  I did some grepping to discover the classes defined by pelican don't appear to be defined anywhere, certainly not any `*.css` files, so perhaps a simple fix is to stylize those classes in the site's `./content/static/css/style.css`.

I'm unfamiliar with the CSS design of the site (what are the `./content/static/css/bootstrap*.css` files for?) but I'm fairly confident this is the right approach.  (It appears the pelican theme css is unused.)

**Comment by Liz315** [comment]
Overcome by new site (coming).
