### ISSUE TITLE
investigate possibly duplicate servers for S4

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#373]
There are duplicate email addresses in the list of servers in the S4 customer AWS account.

**Comment by Liz315** [comment]
This is to actively check that we aren't charging people twice by accident (as opposed to waiting the customer to catch the mistake).

**Comment by exarkun** [comment]
There won't be any more duplicate EC2 servers because we won't boot any more per-subscription EC2 servers at all because of #455.
