### ISSUE TITLE
S3 bucket limit issue preventing new signups

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#384]
placeholder

**Comment by vu3rdd** [comment]
Was wondering if this page has any ways to change it: https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html

**Comment by daira** [comment]
This was fixed some time ago.

**Comment by defuse** [comment]
Yay!

**Comment by daira** [comment]
(There was another issue that never had a ticket, about sign-ups failing due to incompatible dependencies, and that has also just been fixed.)
