### ISSUE TITLE
leastauthority.com fails to serve pages that can completely finish loading

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#389]
At least on Firefox, the red/orange page load circle thingy never stops cycling, indicating that something hasn't stopped loading.

**Comment by defuse** [comment]
I can't reproduce this

**Comment by exarkun** [comment]
I observed something like this, pwiki.js from analytics.leastauthority.com never loads because analytics.leastauthority.com seems to be a blackhole (a server that used to run but doesn't anymore?)

**Comment by exarkun** [comment]
Fixed.
