### ISSUE TITLE
Automate shutting down unused EC2 instances

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#390]
Here are the steps needed:
- find the customer ID (for the time being, the script can just take this as a parameter)
- find the `stripe` JSON file under the `secrets/` directory that has this customer ID
- check that the email address in that file is as expected
- load the `SSEC2` JSON file that is a sibling of the `stripe` file, and get the `publichost` field of that file
- use this (or other information in the SSEC2 file if useful) to terminate the instance.

**Comment by exarkun** [comment]
Dup of #361
