### ISSUE TITLE
ConnectionDone error during license activation step of signup

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#4]
Originally reported by Zancas at [[https://tahoe-lafs.org/trac/tahoe-lafs/ticket/1996]].

Starting...

Automation script started.

Signing up customer for Tahoe-LAFS-on-S3 test B2429CCE...

Activating license...

Failure notification sent for the following error:

ConnectionDone: Connection was closed cleanly.

Command failed with exit code 1.

**Comment by Liz315** [comment]
This is TLoS3 thing and no longer relevant.
