### ISSUE TITLE
fix the bug that is causing multiservercheck processes to pile up

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#401]

**Comment by meejah** [comment]
Some of the output includes "Fatal error: Needed to prompt for a connection or sudo password (host: monitor@REDACTED), but abort-on-prompts was set to True"

Seems at least some of the instances have sudo setup differently than the others. (Although it says it was just running "whoami")

**Comment by exarkun** [comment]
`multiservercheck` is now gone.
