### ISSUE TITLE
Set up S4 signup to accept Bitcoin for S4 subscriptions (already supported by Stripe)

### ISSUE THREAD

**Issue by Liz315** [LeastAuthority/leastauthority.com#459]
Stripe allows for Bitcoin payments, so we could easily enable this feature to accept Bitcoin payments for the S4 service: https://stripe.com/docs/bitcoin

**Comment by exarkun** [comment]
It looks like Stripe doesn't support subscriptions paid via Bitcoin.  We can probably implement the necessary recurring-billing logic on our end but that does make it more work than just a quick change to our Stripe-using JavaScript (as one might have hoped would be sufficient).

**Comment by exarkun** [comment]
Duplicate of #302
