### ISSUE TITLE
Securely transfer the introducer furl to new users

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/leastauthority.com#465]
Currently the service emails a furl to the user once it becomes available (after a long delay).  The introducer furl is somewhat sensitive material (attackers can use it to get storage they don't have to pay for, for example).

We should send this information to the user in a way that makes it harder to steal.

Putting it into a magic wormhole is probably a good solution.

**Comment by Liz315** [comment]
We should offer this for customers using CLI and GUI.

**Comment by exarkun** [comment]
https://github.com/LeastAuthority/leastauthority.com/milestone/11 is going to require this so as that approaches completion we'll probably want to prioritize this up.  We could also do it earlier since CLI users will also be able to use this without the GUI, if they want.

**Comment by exarkun** [comment]
#624 changed signup to be wormhole-based for all signups.
