### ISSUE TITLE
Set up a server for generating wormhole codes

### ISSUE THREAD

**Issue by Liz315** [LeastAuthority/leastauthority.com#490]
Set up a server for generating wormhole codes to display on the website after someone signs up for the S4 service.

**Comment by Liz315** [comment]
It sounds like we already have a Least Authority wormhole server.

**Comment by crwood** [comment]
Yes. The Least Authority wormhole server is now up and running at `ws://wormhole.leastauthority.com:4000/v1` (it was `ws://leastauthority.com:4000/v1`).
