### ISSUE TITLE
Modify Gridsync to use Least Authority’s Magic Wormhole server

### ISSUE THREAD

**Issue by Liz315** [LeastAuthority/leastauthority.com#492]
GridSync needs to know the address of the wormhole server to connect to to resolve wormhole codes.
- Hard-code an address in for now.
- Require users to upgrade to new GridSync later when we change how wormhole server(s) is/are deployed. (possibly centralized with Tahoe-LAFS org in the future)

**Comment by crwood** [comment]
Gridsync is now using `ws://wormhole.leastauthority.com:4000/v1` as its magic-wormhole relay with an `appid`of `tahoe-lafs.org/tahoe-lafs/v1` (which the backend sign-up process will also need to use in order to ensure interoperability).
