### ISSUE TITLE
The certificate is invalid for "www.leastauthority.com".

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#57]
**Synopsis:**

The certificate served by https://www.leastauthority.com is invalid for that domain, because it's specific to `leastauthority.com`.

I expect many users, especially bloggers or journalists who write links, or software which autodetects urls, to insert `www.` so I consider this an important usability problem.

**Close Criteria:**

When you can load "https://www.leastauthority.com" without certificate error and get automatically redirected to "https://leastauthority.com" with at least three different test browsers, this ticket is closable.

**Detail:**

We now have a wildcard cert, so deploying that for `leastauthority.com`, and serving and `HTTP 301` redirect should fix this ticket.  _NOTE:_ I'm not certain `HTTP 301` is the correct strategy; please read up on it and the gotchas.  If we're not certain about it, then `HTTP 302` should be sufficient and safe.

**Comment by Liz315** [comment]
I believe this has been overcome by our recent cert renewal.
