### ISSUE TITLE
add information about digital signatures (for gridsync) to the website

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/leastauthority.com#577]
include basic information about what they are, why we provide them, why the user should check them, and how the user can check them.  currently the wormhole-based post-signup page just links to a generic wikipedia page about digital signatures.  those links should be updated.

**Comment by crwood** [comment]
Okay, I wrote up a document (addressing each of those points) here:

https://github.com/gridsync/gridsync/blob/master/docs/verifying-signatures.md

Please let me know your thoughts and whether you think anything should be added, removed, or changed to improve it.

**Comment by exarkun** [comment]
I think this was fixed by #583
