### ISSUE TITLE
Read-only shell access to leastauthority.com and analytics.leastauthority.com

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#58]
This is an enhancement suggestion, and some amount of low priority work.

It not a bug/regression.

**Synopsis:**

To facilitate "as many eyes as possible" monitoring or verifying our live website, it would be nice to give a larger number of employees access (like me ;-).  However, we want to limit authority to modify the production website to few employees who coordinate tightly.

Meanwhile, we also want to mitigate mistakes in commands from disrupting website availability or data durability, so even employees with the authority to modify the website should typically use a more restrictive authority to view the website.

**Close Criteria:**
1. Create a new user account, perhaps named `websitemonitor`.
2. Ensure that user _does not_ have `sudo` access.
3. Ensure that user _may not_ start or stop processes necessary for operation of the website.
4. Ensure that user _may not_ write any files necessary for the operation of the website, especially user data or logs.
5. Ensure that user _can read_ all logs.
6. Edit that user's `.bashrc` to include something like `ulimit -v $N` where N is the maximum number of bytes any particular login shell of that user should consume at one time.  (I'd ballpartk this should be perhaps one quarter or less of the total available VM RAM.  If it's too small, the shell starts to become unusable.)

**Post Close:**

If that account is too limited (for example, it may not be able to examine production processes with `ps`), we should file separate tickets for the authority increases so that we all understand them.

(An example of fixing `ps` access would be to write a restrictive `sudoers` file to allow that particular command.)

**Comment by Liz315** [comment]
We'll be using monitoring, instead.
