### ISSUE TITLE
The Provisioning of New EC2s takes too long.

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#65]
Even if we have a streamlined payment verification,and debiting process, Users are still forced to wait for a new EC2 to be properly set up.
There are some simple optimizations that can significantly shorten this wait.
(1) Get a recent AMI.  This will make upgrade quicker and remove the need for a post-upgrade reboot (usually).

**Comment by exarkun** [comment]
We no longer provision an EC2 instance for each new subscription.  Instead, with #455, we launch a Docker container - which is quick.
