### ISSUE TITLE
Magic-wormhole appid unity

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/leastauthority.com#705]
Since `tahoe` uses the appid `tahoe-lafs.org/invite` for the `tahoe invite` command, we should switch S4 (in concert with gridsync) to use that same appid by default.

**Comment by exarkun** [comment]
@meejah @crwood Should we set a date to pull the trigger on this and related changes?  What constraints are there, if any?  What is the appid in the last released version of Tahoe-LAFS?

**Comment by crwood** [comment]
I have three sets of changes left for Gridsync (along with some minor documentation updates, new screenshots to add, etc.) before the next release -- all of which I anticipate will be finished at or before the end of this week. That said, I'd be happy to pull the trigger on Monday (March 12) if that works for everyone else.

The last released version of Tahoe-LAFS is fairly old, at this point, and currently lacks the `tahoe invite` feature; the next release, however, is slated to use an appid of [`tahoe-lafs.org/invite`](https://github.com/tahoe-lafs/tahoe-lafs/blob/04b34b6fd2bb112942d2cb8ea41ef11ee4c72347/src/allmydata/scripts/runner.py#L80) (which is consistent with what we now have in the pipeline).

**Comment by crwood** [comment]
Good to go on my end! Gridsync v0.3.0 has been tagged, signed, and released.

Please merge with [PR 713](https://github.com/LeastAuthority/leastauthority.com/pull/713) to update post-signup download links.
