### ISSUE TITLE
Investigate if the `CNAME` for `www.leastauthority.com` → `leastauthority.com` causes piwik or other website problems.

### ISSUE THREAD

**Issue by nathan-at-least** [LeastAuthority/leastauthority.com#71]
**Concern**:

I worry that enough software and users "automagically" prefix `www.` to domains in urls that some fraction of our traffic would have a broken experience.  Right now we know at least the certificate is invalid (see #57), but there may be other issues.  We have a `CNAME` for `www.leastauthority.com` → `leastauthority.com`.

**Test**:

Browse around https://www.leastauthority.com (there will be cert errors; see #57) and then check analytics to see if that traffic was captured correctly.

Also, notice where your browser is redirected to the domain without `www.` prefix.  (The network resource view of the developer consoles in chrome and firefox should reveal this.)

**Mitigating the Test Results**:

If everything works fine _except_ for the certificate error, there is no problem and you should comment on that and close this ticket.

If it confuses analytics or there are other problems, we should implement an `HTTP` 302 or 301 redirect on the server (probably the nginx layer), then we should test the site with that redirection to see if it fixes the problem.

**Comment by Liz315** [comment]
This will be overcome by the cert work and/or the new website.
