### ISSUE TITLE
using a wildcard cert on analytics.leastauthority.com (for example) allows it to spoof the main site

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#73]
If analytics were to be compromised, it could spoof the main leastauthority.com site. We'd actually like to have some privilege separation, especially given that analytics is running a bunch of poorly reviewed PHP scripts. (Note that putting the key to a wildcard cert on leastauthority.com, as proposed in #57 and #71, on the other hand, is fairly harmless unless and until we have privilege separation between the website and other automation.)

The obvious solution is to buy separate certs for analytics.leastauthority.com and monitoring.leastauthority.com. This may require us to be able to receive email at specific addresses for those domains (which is probably just a matter of setting up MX records).

**Comment by Liz315** [comment]
Analytics is gone and we stopped using a wildcard cert.
