### ISSUE TITLE
Use a Custom AMI as a template for SSEC2s 

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#81]
Motivation:

During signups our provisioning automation experiences frequent failure due to unreliable dependencies.   Most recently a provisioning process (and hence the signup which triggered it) failed because of an HTTP 403 response to an `apt-get update` request that was submitted to ubuntu repositories that are maintained by AWS.

This degree of fragility in our core infrastructure is clearly nonviable for automated signup.

Solution:

By creating our own customized AMI which has as much software as possible installed and configured, we can pre-empt such dependency failures.   A second benefit is that deployments based on preconfigured AMIs will be faster than those which require updates after the virtual instance has booted.

Process:

We require the ability to automatically generate our AMIs, to ensure that the process has a rigorous specification.

Here is a description of the manual prototyping I did to learn how to generate AMIs:

`https://github.com/LeastAuthority/leastauthority.com/wiki/Pre-Provisioned-Storage-Server-EC2s-%28SSEC2%29s-Design-for-AMI:--ami-361b5f5f`

Here's the documentation I'll be using to setup the automatic AMI creation script:

`http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html`

**Comment by Liz315** [comment]
Superseded by containerization.
