### ISSUE TITLE
PGP Using Customers Should Receive An Encrypted Confirmation Email Automatically

### ISSUE THREAD

**Issue by zancas** [LeastAuthority/leastauthority.com#85]
This issue is covered by ScrumDo story:  https://www.scrumdo.com/projects/project/s3/iteration/3801#story_112756

The process which needs to be automated is this:

Where the input is an email address "``nick``" is defined as follows
``NICK = sed -e s/@[^@]*$//``

(1) ``grep NICK /home/website/signups.csv | tail -1 | cut  -d ',' -f 7`` > secrets/PGP_fingerprint_NICK

(2) On the email generating system:

   ``gpg --recv-key `tr -d ' ' <PGP_fingerprint_NICK` ``

(3) ``gpg -seaR NICK@EMAIL -o msg.asc confirmation_email_file``

(4)  Send the gpg signed and encrypted email to the email address provided in signups.csv.

**Comment by daira** [comment]
We no longer support PGP/gpg.
