### ISSUE TITLE
update infrastructure deployment to solve: Insecure ciphers are accepted by https://leastauthority.com

### ISSUE THREAD

**Issue by daira** [LeastAuthority/leastauthority.com#92]
The default cipher list allows single-DES.

**Comment by daira** [comment]
This is what we did to fix the production site:
```
sudo dpkg -r python-twisted-core python-twisted-conch python-twisted-mail python-twisted-lore python-twisted-names python-twisted-news python-twisted-runner python-twisted-web python-twisted-words python-nevow python-foolscap landscape-client landscape-common
sudo pip install foolscap service_identity 'Twisted==14.0.2' pem
sudo apt-get install libssl-dev build-essential python-dev libffi-dev
sudo dpkg -r python-openssl
sudo pip install 'pyOpenSSL >= 0.14'
```
and switch to the 92-improve-cipher-list-3 branch.

https://www.ssllabs.com/ssltest/analyze.html?d=leastauthority.com&clearCache=on now gives us an A.

**Comment by daira** [comment]
This ticket should not be closed until we've updated the infrastructure deployment to automatically reach the same state we got to above.

**Comment by david415** [comment]
oh? yes... i agree. we should update the deployment.

**Comment by zookoatleastauthoritycom** [comment]
Judging from this conversation on twitter (https://twitter.com/mik235/status/556201250513895425), the ideal modern cipher suite spec string is `ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA`.

**Comment by daira** [comment]
The default cipher suite list for Twisted 14.0.2 looks perfectly reasonable to me; I'm loath to override it without good reason.

Picking up on another comment on the Twitter thread: we are secure against POODLE attacks on TLS according to the ssllabs test.

**Comment by exarkun** [comment]
We're using that now.  The ssllabs report looks good now.  Considering this fixed.
